export const tasks = [
  {
    id: 1,
    user_id: 101,
    title: "Check Inventory Levels",
    description:
      "Review pantry and cold storage to ensure all ingredients are in stock for the upcoming lunch service. Prepare notes for staff briefing on updated kitchen protocols before service starts. Prepare notes for staff briefing on updated kitchen protocols before service starts. Prepare notes for staff briefing on updated kitchen protocols before service starts. Prepare notes for staff briefing on updated kitchen protocols before service starts.",
    status: "todo",
    created_at: "2025-07-13",
    updated_at: "2025-07-14",
  },
  {
    id: 2,
    user_id: 101,
    title: "Staff Briefing",
    description:
      "Prepare notes for staff briefing on updated kitchen protocols before service starts.",
    status: "in-progress",
    created_at: "2025-07-14",
    updated_at: "2025-07-15",
  },
  {
    id: 3,
    user_id: 101,
    title: "Reorder Supplies",
    description:
      "Place orders for restocking low-supply items identified earlier. Prioritize dairy and produce.",
    status: "done",
    created_at: "2025-07-13",
    updated_at: "2025-07-15",
  },
  {
    id: 4,
    user_id: 101,
    title: "Clean Kitchen Stations",
    description:
      "Ensure all workstations are sanitized before and after prep work.",
    status: "todo",
    created_at: "2025-07-15",
    updated_at: "2025-07-15",
  },
  {
    id: 5,
    user_id: 101,
    title: "Check Expiry Dates",
    description: "Inspect all perishable items and discard expired goods.",
    status: "in-progress",
    created_at: "2025-07-15",
    updated_at: "2025-07-16",
  },
  {
    id: 6,
    user_id: 101,
    title: "Update Menu Board",
    description: "Write today's specials on the board before opening.",
    status: "done",
    created_at: "2025-07-16",
    updated_at: "2025-07-16",
  },
  {
    id: 7,
    user_id: 101,
    title: "Prepare Dough",
    description: "Make fresh dough for tomorrow's pizza service.",
    status: "todo",
    created_at: "2025-07-15",
    updated_at: "2025-07-15",
  },
  {
    id: 8,
    user_id: 101,
    title: "Calibrate Oven",
    description:
      "Check and recalibrate oven temperatures to avoid undercooking.",
    status: "todo",
    created_at: "2025-07-14",
    updated_at: "2025-07-14",
  },
  {
    id: 9,
    user_id: 101,
    title: "Confirm Reservations",
    description: "Call and confirm reservations for tonight's dinner service.",
    status: "in-progress",
    created_at: "2025-07-13",
    updated_at: "2025-07-14",
  },
  {
    id: 10,
    user_id: 101,
    title: "Print Shift Schedules",
    description: "Distribute weekly shift schedules to all kitchen staff.",
    status: "done",
    created_at: "2025-07-12",
    updated_at: "2025-07-13",
  },
  {
    id: 11,
    user_id: 101,
    title: "Deep Clean Refrigerator",
    description: "Defrost and sanitize the walk-in fridge thoroughly.",
    status: "todo",
    created_at: "2025-07-11",
    updated_at: "2025-07-11",
  },
  {
    id: 12,
    user_id: 101,
    title: "Inspect Ventilation",
    description:
      "Check vents and filters for buildup. Schedule maintenance if needed.",
    status: "done",
    created_at: "2025-07-10",
    updated_at: "2025-07-12",
  },
  {
    id: 13,
    user_id: 101,
    title: "Replace Gloves Stock",
    description: "Restock disposable gloves near the prep areas.",
    status: "todo",
    created_at: "2025-07-10",
    updated_at: "2025-07-11",
  },
  {
    id: 14,
    user_id: 101,
    title: "Assign Cleaning Roles",
    description: "Designate cleaning zones and assign roles to evening shift.",
    status: "in-progress",
    created_at: "2025-07-09",
    updated_at: "2025-07-10",
  },
  {
    id: 15,
    user_id: 101,
    title: "Review Feedback Forms",
    description: "Go over feedback from customers and discuss with the team.",
    status: "done",
    created_at: "2025-07-08",
    updated_at: "2025-07-09",
  },
  {
    id: 16,
    user_id: 101,
    title: "Check Equipment Labels",
    description:
      "Ensure all equipment is labeled correctly for inventory purposes.",
    status: "in-progress",
    created_at: "2025-07-07",
    updated_at: "2025-07-08",
  },
  {
    id: 17,
    user_id: 101,
    title: "Sanitize Food Bins",
    description: "Clean and sanitize all food storage bins thoroughly.",
    status: "todo",
    created_at: "2025-07-06",
    updated_at: "2025-07-06",
  },
  {
    id: 18,
    user_id: 101,
    title: "Check Uniform Supplies",
    description: "Verify clean uniforms are ready for all shifts this week.",
    status: "done",
    created_at: "2025-07-06",
    updated_at: "2025-07-07",
  },
  {
    id: 19,
    user_id: 101,
    title: "Create Prep List",
    description: "List items to be prepped before opening shift begins.",
    status: "in-progress",
    created_at: "2025-07-05",
    updated_at: "2025-07-06",
  },
  {
    id: 20,
    user_id: 101,
    title: "Photograph Dishes",
    description: "Take updated photos of dishes for menu marketing.",
    status: "todo",
    created_at: "2025-07-05",
    updated_at: "2025-07-05",
  },
];
